In [2]:
import numpy as np

1

In [3]:
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


2

In [4]:
matrix = np.zeros((3, 3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3

In [5]:
random_big_matrix = np.random.randint(1, 11, size=(5, 5))
print(random_big_matrix)

[[ 9  8 10  4  6]
 [ 2  5  6  5  1]
 [ 9  2  3  4 10]
 [10  7  6 10  6]
 [ 7  6  4  6  6]]


4

In [6]:
random_matrix = np.random.rand(4, 4)
print(random_matrix)

[[0.50391709 0.88046973 0.13382104 0.37858877]
 [0.63218225 0.37581238 0.06345152 0.09980642]
 [0.98008964 0.18215185 0.71835034 0.18004227]
 [0.1547302  0.87805631 0.7283859  0.92442688]]


5

In [7]:
first_random_vector = np.random.randint(1, 11, size=(5))
second_random_vector = np.random.randint(1, 11, size=(5))
print(first_random_vector)
print(second_random_vector)
print(first_random_vector+second_random_vector)
print(first_random_vector-second_random_vector)
print(first_random_vector*second_random_vector)

[ 9  8 10  7  6]
[10  8  7  9  9]
[19 16 17 16 15]
[-1  0  3 -2 -3]
[90 64 70 63 54]


6

In [8]:
first_sevenSize_vector = np.array([4, 3, 2, 6, 5, 8, 4], dtype=int)
second_sevenSize_vector = np.array([6, 5, 9, 2, 4, 1, 10], dtype=int)
print(np.dot(first_sevenSize_vector, second_sevenSize_vector))

137


7

In [9]:
first_random_matrix = np.random.randint(1, 11, size=(2, 2))
second_random_matrix = np.random.randint(1, 11, size=(2, 3))
print(first_random_matrix)
print(second_random_matrix)
print(np.dot(first_random_matrix, second_random_matrix))

[[ 9  6]
 [ 3 10]]
[[ 5 10  5]
 [ 3  2  2]]
[[ 63 102  57]
 [ 45  50  35]]


8

In [10]:
matrix = np.random.randint(1, 11, size=(3, 3))
print(matrix)
print(np.linalg.inv(matrix))

[[ 6 10  6]
 [ 9  2  7]
 [10  1  4]]
[[ 0.00357143 -0.12142857  0.20714286]
 [ 0.12142857 -0.12857143  0.04285714]
 [-0.03928571  0.33571429 -0.27857143]]


9

In [11]:
matrixT = np.random.rand(4, 4)
print(matrixT)
print(matrixT.T)

[[0.04183872 0.31261479 0.28270704 0.39254933]
 [0.19235814 0.32960665 0.49111207 0.63767101]
 [0.61133263 0.77776648 0.86890131 0.84574955]
 [0.17869204 0.67586626 0.84256464 0.27715269]]
[[0.04183872 0.19235814 0.61133263 0.17869204]
 [0.31261479 0.32960665 0.77776648 0.67586626]
 [0.28270704 0.49111207 0.86890131 0.84256464]
 [0.39254933 0.63767101 0.84574955 0.27715269]]


10

In [12]:
matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
vector_4 = np.random.randint(1, 11, size=4)
print(matrix_3x4)
print(vector_4)
print(np.dot(matrix_3x4, vector_4))

[[ 7  1  8 10]
 [ 4  5  6  9]
 [ 5  6  7  3]]
[10  2  9  9]
[234 185 152]


11

In [13]:
matrix_2x3 = np.random.rand(2, 3)
vector_3 = np.random.rand(3)
print(matrix_2x3)
print(vector_3)
print(np.dot(matrix_2x3, vector_3))

[[0.07121468 0.34131588 0.14082286]
 [0.9826964  0.27544588 0.82298242]]
[0.88147172 0.67360997 0.57010532]
[0.37297136 1.52094883]


12

In [14]:
first_matrix_2x2 = np.random.randint(1, 11, size=(2, 2))
second_matrix_2x2 = np.random.randint(1, 11, size=(2, 2))
print(first_matrix_2x2)
print(second_matrix_2x2)
print(first_matrix_2x2 * second_matrix_2x2)

[[6 4]
 [2 7]]
[[ 6 10]
 [ 6  8]]
[[36 40]
 [12 56]]


13

In [15]:
first_matrix_2x2 = np.random.randint(1, 11, size=(2, 2))
second_matrix_2x2 = np.random.randint(1, 11, size=(2, 2))
print(first_matrix_2x2)
print(second_matrix_2x2)
print(np.dot(first_matrix_2x2, second_matrix_2x2))

[[ 9 10]
 [10  1]]
[[ 5 10]
 [ 7  9]]
[[115 180]
 [ 57 109]]


14

In [16]:
matrix_5x5 = np.random.randint(1, 101, size=(5, 5))
print(matrix_5x5)
print(matrix_5x5.sum())

[[96 70 62 46  1]
 [93 39 53 46 55]
 [53 13 58 86 13]
 [35 60 71  4 81]
 [92 45 34 30 82]]
1318


15

In [17]:
first_matrix_4x4 = np.random.randint(1, 11, size=(4, 4))
second_matrix_4x4 = np.random.randint(1, 11, size=(4, 4))
print(first_matrix_4x4)
print(second_matrix_4x4)
print(first_matrix_4x4 - second_matrix_4x4)

[[10  3  7  4]
 [ 9  8  4  5]
 [ 9  3  2  2]
 [ 1  2 10  7]]
[[10  3  6  1]
 [ 6  1  2  7]
 [ 1  8  2  3]
 [ 8  5  3  8]]
[[ 0  0  1  3]
 [ 3  7  2 -2]
 [ 8 -5  0 -1]
 [-7 -3  7 -1]]


16

In [18]:
matrix_3x3 = np.random.rand(3, 3)
print(matrix_3x3)
print((np.sum(matrix_3x3, axis=1)).reshape(-1, 1))

[[0.00202759 0.28118458 0.50444302]
 [0.13207187 0.79734871 0.04470926]
 [0.43135954 0.79284628 0.09653151]]
[[0.7876552 ]
 [0.97412985]
 [1.32073733]]


17

In [19]:
matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
print(matrix_3x4)
print(matrix_3x4 ** 2)

[[ 2  8 10  6]
 [ 4  8  7  2]
 [ 7  5 10 10]]
[[  4  64 100  36]
 [ 16  64  49   4]
 [ 49  25 100 100]]


18

In [20]:
vector_4 = np.random.randint(1, 51, size=(4))
print(vector_4)
print(np.sqrt(vector_4))

[ 9  3 41 27]
[3.         1.73205081 6.40312424 5.19615242]
